### ISSUE TITLE
`getGlyphViewDisplaySettings()['Rulers']` gives an error in RF 4

### ISSUE THREAD

**Issue by RafalBuchner** [okay-type/Markymark-roboFontExt#2]
`getGlyphViewDisplaySettings()['Rulers']` gives an error in RF 4 (line 106 of mark-in-glyphview.py).
I think `getGlyphViewDisplaySettings()['Guidelines']` should work.

**Comment by okay-type** [comment]
Thanks, Rafal. This extension has been rewritten for Robofont 4 here: https://gist.github.com/okay-type/9111826ae6571d56905538c98d5de369
